import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { getCssText } from '@/styles'
import { globalStyles } from '../styles/global'

import Image from 'next/image'
import { Container, Header } from '../styles/pages/app'

globalStyles()

const roboto = Roboto({
  weight: ['400', '700'], // Selecionando os pesos desejados
  subsets: ['latin'],
  variable: '--font-roboto', // Definição da variável CSS
})

export const metadata: Metadata = {
  title: 'Ignite Shop by Caio - Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body
        className={`${roboto.variable} antialiased`} // Aplicando a fonte Roboto
      >
        <Container>
          <Header>
            <Image src="/logo.svg" width={150} height={50} alt="Logo" />
          </Header>

          {children}
        </Container>
      </body>
    </html>
  )
}
